<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config [
	<!ELEMENT config (package*)>
	<!ELEMENT package (property*)>
	<!ELEMENT property (#PCDATA)>
	<!ATTLIST package name ID #REQUIRED>
	<!ATTLIST property name CDATA #REQUIRED>
]>

<config>
	<package name="path">
		<property name="ROOT"></property>
		<property name="UPLOAD_ROOT"></property>
	</package>

	<package name="sys">
		<property name="SERVER_ADDRESS"></property>
		<property name="URL_ROOT"></property>
		<property name="LOCALE">zh_CN</property>
	</package>
	
	<package name="login_url">
		<property name="web_login_url"></property>
		<property name="back_login_url">index</property>
	</package>
	
	<package name="action">
		<property name="DATE_CONVERTER">yyyy-MM-dd</property>
	</package>
	
	<package name="log">
		<property name="APP">huixin</property>
	</package>

    <package name="security">
        <property name="scan_packages">com.huixin</property>
    </package>
</config>


